### ISSUE TITLE
$ - string interpolation

### ISSUE THREAD

**Issue by KHajili98** [fidan-xanlarovaa/PragmatechCsharpProject#1]
Tasklarda ciddi problem yoxdur. **String Interpolation** arashdirmaginizi meslehet gorerdim ve sonra bu tasklara tetbiq ederdiniz.

**Comment by fidan-xanlarovaa** [comment]
Salam,diqqətə alacam.Təşəkkür edirəm.

**Comment by KHajili98** [comment]
Aha novbeti derse kimi tetbiq edin. Baxdim hele de tetbiq etmemisiniz.

**Comment by KHajili98** [comment]
Aha novbeti derse kimi tetbiq edin. Baxdim hele de tetbiq etmemisiniz.
