### ISSUE TITLE
USER

### ISSUE THREAD

**Issue by parvizrovshanaliyev** [fidan-xanlarovaa/PragmatechCsharpProject#16]
![image](https://user-images.githubusercontent.com/44087592/132939923-fc117a09-22e6-4105-8d06-81342bc54ff5.png)
user cedvelinde username ve pass olmalidir her zaman , hemcinin ad soyad kimi fieldler optioanl deyil requried qeyd olunmalidi

**Comment by fidan-xanlarovaa** [comment]
done
