### ISSUE TITLE
folder structure 

### ISSUE THREAD

**Issue by KHajili98** [fidan-xanlarovaa/PragmatechCsharpProject#4]
folderleri heftelere uygun bolusdursen ela olar... week01de butun tasklar ayri... week02 tasklari bir folder altinda, week03 ayri..  Novbeti heftede ona uygun sistemlesdir

**Comment by fidan-xanlarovaa** [comment]
done ✅

**Comment by KHajili98** [comment]
Week3_Task1-de Week3 bawliqdan silersen vaxtin olanda Week3 papkasina girende sadece Task1, Task2... olaraq olsa cox yaxwi olar..
