### ISSUE TITLE
week 03- task03

### ISSUE THREAD

**Issue by KHajili98** [fidan-xanlarovaa/PragmatechCsharpProject#5]
` if (numberOfAttempts == 5)
                {
                    Console.WriteLine($"Your guessing chance is over. The number was {random}");
                    break;
                }`

bundan elave her loopda nece sansiniz qaldi deye mesaj versen cliente daha yaxsi olardi. meselen 4 sansiniz qaldi,,, 3 sansiniz qaldi... Mecburi deyil amma client ucun daha anlasiqli olardi.

**Comment by fidan-xanlarovaa** [comment]
done✅
